# Generated by Django 2.0.4 on 2018-08-20 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Typeofinquiry',
            fields=[
                ('inquirytype_id', models.AutoField(primary_key=True, serialize=False)),
                ('inquirytype', models.CharField(max_length=20)),
            ],
        ),
    ]
