# Generated by Django 2.0.4 on 2018-08-20 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boardtype',
            fields=[
                ('boardtype_id', models.AutoField(primary_key=True, serialize=False)),
                ('boardname', models.CharField(choices=[('1:1문의', '1:1문의'), ('리뷰', '리뷰'), ('faq', 'faq')], max_length=1)),
            ],
        ),
    ]
