# Generated by Django 2.0.4 on 2018-08-20 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardtype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardtype',
            name='boardname',
            field=models.CharField(choices=[('1:1문의', '1:1문의'), ('리뷰', '리뷰'), ('faq', 'faq')], max_length=10),
        ),
    ]
