# Generated by Django 2.0.4 on 2018-08-20 04:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petsitterapplication',
            fields=[
                ('application_id', models.AutoField(primary_key=True, serialize=False)),
                ('informationapproval', models.BooleanField(default=False)),
                ('answer1', models.CharField(choices=[('무직', '무직'), ('주부', '주부'), ('자영업', '자영업'), ('회사원', '회사원'), ('학생', '학생'), ('기타', '기타')], max_length=20)),
                ('answer2', models.CharField(choices=[('1', '예'), ('2', '아니요')], max_length=1)),
                ('answer3', models.CharField(choices=[('1', '1일'), ('2', '2일~7일'), ('3', '7일~23일'), ('4', '14일~20일'), ('5', '21일~31일')], max_length=1)),
                ('answer4', models.CharField(choices=[('1', '예'), ('2', '아니요')], max_length=1)),
                ('answer5', models.CharField(choices=[('1', '예'), ('2', '아니요')], max_length=1)),
                ('answer6', models.CharField(choices=[('1', '예'), ('2', '아니요')], max_length=1)),
                ('answer7', models.CharField(max_length=200)),
                ('answer8', models.CharField(max_length=200)),
                ('answer9', models.CharField(max_length=200)),
                ('applicationpass', models.CharField(choices=[('심사중', '심사중'), ('합격', '합격'), ('불합격', '불합격')], max_length=20)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
