# Generated by Django 2.0.4 on 2018-08-20 05:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('paymentmethod', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_id', models.AutoField(primary_key=True, serialize=False)),
                ('paymentdate', models.DateTimeField(auto_now_add=True)),
                ('approvalnumber', models.CharField(max_length=50)),
                ('depositnumber', models.CharField(max_length=50)),
                ('depositbank', models.CharField(choices=[('1', '국민은행'), ('2', '신한은행'), ('3', '우리은행'), ('4', '하나은행'), ('5', '케이뱅크'), ('6', '카카오뱅크'), ('7', '산업은행'), ('8', '기업은행'), ('9', '한국수출입은행'), ('10', '농협은행'), ('11', '신협은행'), ('12', '대구은행'), ('13', '부산은행'), ('14', '경남은행'), ('15', '광주은행'), ('16', '전북은행'), ('17', '제주은행')], max_length=1)),
                ('totalprice', models.IntegerField()),
                ('paymentmethod_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='paymentmethod.Paymentmethod')),
                ('request_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
        ),
    ]
