# Generated by Django 2.0.4 on 2018-08-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('caringweight', '0002_auto_20180820_1414'),
        ('petsitter', '0001_initial'),
        ('review', '0001_initial'),
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sitterinforegistration',
            fields=[
                ('sitterinforegistration_id', models.AutoField(primary_key=True, serialize=False)),
                ('posted', models.BooleanField(default=True)),
                ('posteddate', models.DateTimeField(auto_now_add=True)),
                ('attachment', models.FileField(upload_to='uploads/')),
                ('nearbysubwaystation', models.CharField(max_length=100)),
                ('cohabitationstatus', models.BooleanField(default=True)),
                ('childstatusunder14', models.BooleanField(default=True)),
                ('introduction', models.TextField()),
                ('board_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='review.Review')),
                ('caringweight_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='caringweight.Caringweight')),
                ('petsitter_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='petsitter.Petsitter')),
                ('request_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
        ),
    ]
