# Generated by Django 2.0.4 on 2018-08-25 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterinforegistration', '0003_sitterinforegistration_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterinforegistration',
            name='ppp',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
