# Generated by Django 2.0.4 on 2018-08-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sitterinforegistration', '0005_sitterinforegistration_sitterlevel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitterinforegistration',
            name='sitterlevel',
            field=models.CharField(choices=[('우수', '우수'), ('보통', '보통'), ('신규', '신규')], max_length=10, null=True),
        ),
    ]
