# Generated by Django 2.0.4 on 2018-08-25 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sitterinforegistration', '0006_auto_20180826_0054'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitterinforegistration',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
