# Generated by Django 2.0.4 on 2018-08-20 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('name', models.CharField(max_length=50)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('birthdate', models.DateField()),
                ('phonenumber', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=50)),
                ('address1', models.CharField(max_length=50)),
                ('address2', models.CharField(max_length=50)),
                ('address3', models.CharField(max_length=50)),
                ('profile', models.FileField(null=True, upload_to='uploads/')),
                ('regdate', models.DateTimeField(auto_now=True)),
                ('joinapproval', models.BooleanField(default=True)),
                ('membershiplevel', models.CharField(choices=[('member', 'Member'), ('sitter', 'Sitter'), ('manager', 'Manager')], max_length=1)),
            ],
        ),
    ]
