# Generated by Django 2.0.4 on 2018-08-20 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membershiplevel',
            field=models.CharField(choices=[('member', 'Member'), ('sitter', 'Sitter'), ('manager', 'Manager')], max_length=10),
        ),
    ]
