# Generated by Django 2.0.6 on 2018-09-14 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('member', '0003_auto_20180915_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='membershiplevel',
            field=models.CharField(choices=[('member', 'Member'), ('sitter', 'Sitter'), ('manager', 'Manager')], default='member', max_length=10),
        ),
        migrations.AlterField(
            model_name='member',
            name='sex',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=1),
        ),
    ]
