# Generated by Django 2.0.4 on 2018-08-20 04:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('additionalservicetype', '0002_auto_20180820_1316'),
    ]

    operations = [
        migrations.CreateModel(
            name='Additionalservice',
            fields=[
                ('additionalservice_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('price', models.IntegerField()),
                ('additionalservicetype_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='additionalservicetype.Additionalservicetype')),
            ],
        ),
    ]
