# Generated by Django 2.1.3 on 2018-11-20 06:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=50, verbose_name='회원의 현재 직업')),
                ('permission', models.BooleanField(default=True, verbose_name='가족들의 동의를 구하셨나요?')),
                ('whether_smoker', models.BooleanField(default=True, verbose_name='가족중에 흡연자가 있나요?')),
                ('maximum_caring_period', models.BooleanField(default=True, verbose_name='한달 내에 최대돌봄기간은 어느정도인가요?')),
                ('minors_status', models.BooleanField(default=True, verbose_name='식구중에 미성년자가 있습니까?')),
                ('sitter_career', models.BooleanField(default=True, verbose_name='시터로 활동한 적이 있습니까?')),
                ('time_together', models.IntegerField(default=True, verbose_name='반려동물과 함께한 시간은 몇개월 입니까?')),
                ('pet_count', models.IntegerField(default=True, verbose_name='현재 키우고있는 반려동물 수')),
                ('experience', models.TextField(max_length=1000, verbose_name='반려동물과 함께해서 좋았던 기억을 입력해주세요')),
                ('responsibility', models.BooleanField(default=True, verbose_name='펫시터로 최선을 다할것을 약속하십니까?')),
            ],
        ),
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_type', models.CharField(choices=[('1', '1:1문의'), ('2', 'FAQ')], max_length=10, verbose_name='게시판 종류')),
                ('title', models.CharField(max_length=100, verbose_name='게시판제목')),
                ('contents', models.TextField(max_length=1000, verbose_name='게시판내용')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('attachments', models.FileField(upload_to='uploads/', verbose_name='첨부파일')),
                ('hit', models.IntegerField(default=0, verbose_name='게시판 조회수')),
            ],
        ),
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='펫 이름')),
                ('species', models.CharField(max_length=50, verbose_name='견종')),
                ('birth_date', models.DateField(verbose_name='생일')),
                ('weight', models.IntegerField(default=10, verbose_name='몸무게')),
                ('sex', models.CharField(choices=[('M', '남자'), ('F', '여자')], max_length=5, verbose_name='성별')),
                ('neutralization', models.BooleanField(default=True, verbose_name='중성화유무')),
                ('profile', models.FileField(upload_to='uploads/', verbose_name='프로필사진')),
                ('vaccination', models.BooleanField(verbose_name='예방접종유무')),
            ],
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_date', models.DateTimeField(verbose_name='신청한 날짜')),
                ('start_datetime', models.DateTimeField(verbose_name='돌봄시작날짜')),
                ('end_datetime', models.DateTimeField(verbose_name='돌봄마침날짜')),
                ('free_services', models.CharField(max_length=100, verbose_name='무료 서비스')),
                ('paid_services', models.CharField(max_length=100, verbose_name='유료 서비스')),
                ('precautions', models.CharField(max_length=100, verbose_name='돌봄 주의사항')),
                ('progress', models.CharField(max_length=100, verbose_name='진행상황')),
                ('total_price', models.IntegerField(default=0, verbose_name='총가격')),
                ('dog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Dog', verbose_name='예약이 신청된 동물')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='게시판제목')),
                ('contents', models.TextField(max_length=1000, verbose_name='게시판내용')),
                ('star_score', models.CharField(choices=[('1', '1점'), ('2', '2점'), ('3', '3점'), ('4', '4점'), ('5', '5점')], max_length=1, verbose_name='별점')),
            ],
        ),
        migrations.CreateModel(
            name='Sitter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=100, verbose_name='계좌번호')),
                ('bank_name', models.CharField(choices=[('1', '국민은행'), ('2', '신한은행'), ('3', '우리은행'), ('4', '하나은행'), ('5', '케이뱅크'), ('6', '카카오뱅크'), ('7', '산업은행'), ('8', '기업은행'), ('9', '한국수출입은행'), ('10', '농협은행'), ('11', '신협은행'), ('12', '대구은행'), ('13', '부산은행'), ('14', '경남은행'), ('15', '광주은행'), ('16', '전북은행'), ('17', '제주은행')], max_length=10, verbose_name='은행명')),
                ('introduction', models.CharField(max_length=200, verbose_name='시터소개')),
                ('free_services', models.CharField(max_length=100, verbose_name='무료 서비스')),
                ('paid_services', models.CharField(max_length=100, verbose_name='유료 서비스')),
                ('unit_price', models.IntegerField(default=0, verbose_name='시급')),
            ],
        ),
        migrations.CreateModel(
            name='SitterSchedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.CharField(choices=[('1', '1월'), ('2', '2월'), ('3', '3월'), ('4', '4월'), ('5', '5월'), ('6', '6월'), ('7', '7월'), ('8', '8월'), ('9', '9월'), ('10', '10월'), ('11', '11월'), ('12', '12월')], max_length=100, verbose_name='시터가능달')),
                ('day', models.CharField(choices=[('1', '월요일'), ('2', '화요일'), ('3', '수요일'), ('4', '목요일'), ('5', '금요일'), ('6', '토요일'), ('7', '일요일')], max_length=100, verbose_name='시터가능요일')),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Sitter', verbose_name='시터')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='회원 이름')),
                ('sex', models.CharField(choices=[('M', '남자'), ('F', '여자')], default='F', max_length=1, verbose_name='회원 성별')),
                ('birth_date', models.DateField(verbose_name='회원 생일')),
                ('phone_number', models.CharField(max_length=20, verbose_name='회원 핸드폰번호')),
                ('email', models.EmailField(max_length=50, verbose_name='회원 이메일')),
                ('address1', models.CharField(max_length=50, verbose_name='회원 주소1')),
                ('address2', models.CharField(max_length=50, verbose_name='회원 주소2')),
                ('profile', models.FileField(upload_to='uploads/', verbose_name='회원 사진')),
                ('registration_datetime', models.DateTimeField(auto_now=True, verbose_name='회원가입일')),
                ('membership_level', models.CharField(choices=[('member', '일반회원'), ('sitter', '시터'), ('manager', '관리자')], default='member', max_length=10, verbose_name='회원 등급')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='유저')),
            ],
        ),
        migrations.AddField(
            model_name='sitter',
            name='user_profile',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile', verbose_name='시터이름'),
        ),
        migrations.AddField(
            model_name='review',
            name='sitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Sitter', verbose_name='시터'),
        ),
        migrations.AddField(
            model_name='review',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile', verbose_name='리뷰작성자'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='sitter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Sitter', verbose_name='예약을 신청받은 시터'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile', verbose_name='예약을 신청한 회원'),
        ),
        migrations.AddField(
            model_name='board',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile', verbose_name='글쓴이'),
        ),
        migrations.AddField(
            model_name='application',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile', verbose_name='지원서를 작성한 회원'),
        ),
    ]
