# Generated by Django 2.1.3 on 2018-11-20 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='application',
            old_name='user_profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='board',
            old_name='user_profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='reservation',
            old_name='user_profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_profile',
            new_name='userprofile',
        ),
        migrations.RenameField(
            model_name='sitter',
            old_name='user_profile',
            new_name='userprofile',
        ),
    ]
