# Generated by Django 2.1.3 on 2018-11-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_auto_20181120_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='attachments',
            field=models.FileField(null=True, upload_to='uploads/', verbose_name='첨부파일'),
        ),
    ]
