# Generated by Django 2.1.3 on 2018-11-20 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_auto_20181120_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='pet_q1',
            field=models.CharField(default='', max_length=50, verbose_name='다른 강아지에 대한 반응'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dog',
            name='pet_q2',
            field=models.CharField(default='', max_length=50, verbose_name='다른 사람에 대한 반응'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='board',
            name='board_type',
            field=models.CharField(choices=[('qna', '1:1문의'), ('faq', 'FAQ')], max_length=10, verbose_name='게시판 종류'),
        ),
    ]
