# Generated by Django 2.1.3 on 2018-11-20 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_auto_20181120_1852'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dog',
            old_name='pet_32',
            new_name='pet_q3',
        ),
    ]
