# Generated by Django 2.1.3 on 2018-11-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0006_auto_20181120_1852'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='age',
            field=models.IntegerField(default=0, verbose_name='나이'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='dog',
            name='neutralization',
            field=models.BooleanField(default=True, verbose_name='중성화 여부'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='profile',
            field=models.ImageField(upload_to='dog_images/', verbose_name='프로필 사진'),
        ),
        migrations.AlterField(
            model_name='dog',
            name='weight',
            field=models.FloatField(verbose_name='몸무게'),
        ),
    ]
