# Generated by Django 2.1.3 on 2018-11-20 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0008_auto_20181120_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='dog',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='homepage.UserProfile', verbose_name='견주'),
            preserve_default=False,
        ),
    ]
