# Generated by Django 2.1.3 on 2018-11-20 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0009_dog_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='sitter',
            name='care_zone',
            field=models.CharField(default=None, max_length=100, verbose_name='돌봄 공간'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='day_price',
            field=models.IntegerField(default=0, verbose_name='일당'),
        ),
        migrations.AddField(
            model_name='sitter',
            name='housemate_situation',
            field=models.CharField(default=None, max_length=100, verbose_name='가족 동거 유무'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='pet_situation',
            field=models.CharField(default=None, max_length=100, verbose_name='다른 반려동물 유무'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='qna',
            field=models.TextField(default=None, max_length=1000, verbose_name='QnA'),
            preserve_default=False,
        ),
    ]
