# Generated by Django 2.1.3 on 2018-11-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0010_auto_20181120_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dog',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='sitter',
            name='intro',
            field=models.CharField(default='', max_length=200, verbose_name='한 줄 소개'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sitter',
            name='profile',
            field=models.ImageField(default=None, upload_to='profile/', verbose_name='프로필 사진'),
            preserve_default=False,
        ),
    ]
