# Generated by Django 2.1.3 on 2018-11-20 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0011_auto_20181120_2039'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitter',
            name='intro',
        ),
    ]
