# Generated by Django 2.1.3 on 2018-11-20 13:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0012_remove_sitter_intro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='end_datetime',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='free_services',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='paid_services',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='reservation_date',
        ),
        migrations.RemoveField(
            model_name='reservation',
            name='start_datetime',
        ),
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='돌봄마침날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='reservation_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='신청한 날짜'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reservation',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='돌봄시작날짜'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservation',
            name='total_price',
            field=models.IntegerField(default=0, verbose_name='총 가격'),
        ),
        migrations.AlterField(
            model_name='sitter',
            name='bank_name',
            field=models.CharField(choices=[('국민은행', '국민은행'), ('신한은행', '신한은행'), ('우리은행', '우리은행'), ('하나은행', '하나은행'), ('케이뱅크', '케이뱅크'), ('카카오뱅크', '카카오뱅크'), ('산업은행', '산업은행'), ('기업은행', '기업은행'), ('한국수출입은행', '한국수출입은행'), ('농협은행', '농협은행'), ('신협은행', '신협은행'), ('대구은행', '대구은행'), ('부산은행', '부산은행'), ('경남은행', '경남은행'), ('광주은행', '광주은행'), ('전북은행', '전북은행'), ('제주은행', '제주은행')], max_length=10, verbose_name='은행명'),
        ),
    ]
