# Generated by Django 2.1.3 on 2018-11-20 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0013_auto_20181120_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_no',
            field=models.CharField(default='00000000', max_length=8, verbose_name='예약번호'),
            preserve_default=False,
        ),
    ]
