# Generated by Django 2.1.3 on 2018-11-21 04:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0014_reservation_reservation_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reservation',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='homepage.Reservation', verbose_name='예약'),
            preserve_default=False,
        ),
    ]
