# Generated by Django 2.1.3 on 2018-11-21 04:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0015_review_reservation'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='sitter',
        ),
        migrations.RemoveField(
            model_name='review',
            name='star_score',
        ),
        migrations.RemoveField(
            model_name='review',
            name='userprofile',
        ),
        migrations.AddField(
            model_name='review',
            name='created_datetime',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='작성일'),
            preserve_default=False,
        ),
    ]
