# Generated by Django 2.1.3 on 2018-11-21 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0017_auto_20181121_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='written_review',
            field=models.BooleanField(default=False, verbose_name='리뷰 작성 여부'),
        ),
    ]
