# Generated by Django 2.1.3 on 2018-11-21 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0018_reservation_written_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_datetime', models.DateTimeField(auto_now_add=True, verbose_name='작성일')),
                ('merchant_uid', models.CharField(max_length=100, verbose_name='거래 번호')),
                ('amount', models.IntegerField(verbose_name='결제 금액')),
                ('apply_num', models.CharField(max_length=100, verbose_name='승인번호')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.Reservation', verbose_name='예약')),
            ],
        ),
    ]
