# Generated by Django 2.1.3 on 2018-11-21 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0019_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='application',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='합격 전송 여부'),
        ),
        migrations.AlterField(
            model_name='application',
            name='maximum_caring_period',
            field=models.IntegerField(verbose_name='한달 내에 최대돌봄기간은 어느정도인가요?'),
        ),
    ]
