# Generated by Django 2.1.3 on 2018-11-21 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0020_auto_20181121_1446'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.CharField(default='00000', max_length=10, verbose_name='우편 번호'),
            preserve_default=False,
        ),
    ]
