# Generated by Django 2.0.4 on 2018-08-20 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('request', '0001_initial'),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('board_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='board.Board')),
                ('grade', models.CharField(choices=[('1', '1점'), ('2', '2점'), ('3', '3점'), ('4', '4점'), ('5', '5점')], max_length=1)),
                ('payment_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='request.Request')),
            ],
        ),
    ]
