# Generated by Django 2.0.4 on 2018-08-20 03:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dog',
            fields=[
                ('dog_id', models.AutoField(primary_key=True, serialize=False)),
                ('dogname', models.CharField(max_length=50)),
                ('species', models.CharField(max_length=50)),
                ('birthdate', models.DateField()),
                ('weight', models.IntegerField(default=10)),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('neutralization', models.BooleanField(default=True)),
                ('profile', models.FileField(upload_to='uploads/')),
                ('vaccination', models.BooleanField(default=True)),
                ('id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
