# Generated by Django 2.0.4 on 2018-08-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('additionalservicetype', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalservicetype',
            name='type',
            field=models.CharField(choices=[('free', '무료'), ('charge', '유료')], max_length=10),
        ),
    ]
