# Generated by Django 2.0.4 on 2018-08-20 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Basicunitprice',
            fields=[
                ('unitprice_id', models.AutoField(max_length=30, primary_key=True, serialize=False)),
                ('time', models.IntegerField(default=0)),
                ('price', models.IntegerField(default=0)),
                ('fee', models.IntegerField(default=0)),
            ],
        ),
    ]
