# Generated by Django 2.0.4 on 2018-08-20 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('request_id', models.AutoField(primary_key=True, serialize=False)),
                ('requestdate', models.DateTimeField()),
                ('approvalwhether', models.BooleanField(default=False)),
                ('approvaldate', models.DateTimeField()),
                ('premeetdate', models.DateTimeField()),
                ('carestartdate', models.DateTimeField()),
                ('careenddate', models.DateTimeField()),
                ('totalprice', models.IntegerField(default=0)),
                ('dog_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='dog.Dog')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
