# Generated by Django 2.0.4 on 2018-08-20 04:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('petsitterapplication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Petsittertraining',
            fields=[
                ('training_id', models.AutoField(primary_key=True, serialize=False)),
                ('whether', models.CharField(choices=[('이수중', '이수중'), ('합격', '합격'), ('불합격', '불합격')], max_length=10)),
                ('area', models.CharField(choices=[('서울', '서울'), ('경기', '경기'), ('인천', '인천')], max_length=10)),
                ('date', models.DateField()),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='petsitterapplication.Petsitterapplication')),
            ],
        ),
    ]
