# Generated by Django 2.0.4 on 2018-08-20 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Educationpaymentmethod',
            fields=[
                ('epaymentmethod_id', models.AutoField(primary_key=True, serialize=False)),
                ('method', models.CharField(choices=[('카드결제', '카드결제'), ('계좌이체', '계좌이체'), ('무통장입금', '무통장입금')], max_length=1)),
            ],
        ),
    ]
