# Generated by Django 2.0.4 on 2018-08-20 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('educationpaymentmethod', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationpaymentmethod',
            name='method',
            field=models.CharField(choices=[('카드결제', '카드결제'), ('계좌이체', '계좌이체'), ('무통장입금', '무통장입금')], max_length=10),
        ),
    ]
