# Generated by Django 2.0.4 on 2018-08-20 05:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('board', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('commentdate', models.DateTimeField(auto_now_add=True)),
                ('comments', models.TextField(max_length=200)),
                ('board_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='board.Board')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
