# Generated by Django 2.0.4 on 2018-08-20 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caringweight',
            fields=[
                ('caringweight_id', models.AutoField(primary_key=True, serialize=False)),
                ('caringweight', models.CharField(choices=[('1kg이상', '1kg~'), ('10kg이상', '10kg~'), ('20kg이상', '20kg~')], max_length=1)),
                ('weightprice', models.IntegerField(default=0)),
            ],
        ),
    ]
