# Generated by Django 2.0.4 on 2018-08-20 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caringweight', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caringweight',
            name='caringweight',
            field=models.CharField(choices=[('1kg이상', '1kg~'), ('10kg이상', '10kg~'), ('20kg이상', '20kg~')], max_length=10),
        ),
    ]
