# Generated by Django 2.0.4 on 2018-08-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('caringweight', '0002_auto_20180820_1414'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caringweight',
            name='caringweight',
            field=models.CharField(choices=[('10kg미만', '~10kg'), ('20kg미만', '~20kg'), ('20kg이상', '20kg~')], max_length=10),
        ),
    ]
