# Generated by Django 2.0.4 on 2018-08-20 04:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('boardtype', '0002_auto_20180820_1349'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('board_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=400)),
                ('contents', models.TextField()),
                ('creatingdate', models.DateTimeField(auto_now_add=True)),
                ('attachments', models.FileField(null=True, upload_to='uploads/')),
                ('hit', models.IntegerField(default=0)),
                ('boardtype_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='boardtype.Boardtype')),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
