# Generated by Django 2.0.4 on 2018-08-20 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Petsittersearchcondition',
            fields=[
                ('searchterms_id', models.AutoField(primary_key=True, serialize=False)),
                ('termsname', models.CharField(max_length=50)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
